name: smart_coverage
description: A modern Dart CLI tool for intelligent coverage analysis with AI-powered insights for Flutter/Dart projects.
version: 0.0.1
homepage: "https://github.com/Dammyololade/smart_coverage"

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  yaml: ^3.1.2
  path: ^1.9.0
  process: ^5.0.2
  http: ^1.2.1
  coverage: ^1.9.2
  flutter_lints: ^6.0.0
  markdown: ^7.2.2

dev_dependencies:
  build_runner: ^2.6.0
  build_verify: ^3.1.1
  build_version: ^2.1.2
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^10.0.0

executables:
  smart_coverage:
